### PR TITLE
Fix Force_ delete in Stress inheritance

### LINKED ISSUE #133: Bus error in adapter destruction
Currently working with the `Stress` data field and OpenFOAM 7, I face the following error, when the simulation has finished: 
```
---[preciceAdapter] [DEBUG] Destroying the preCICE solver interface...
---[preciceAdapter] [DEBUG] Deleting the interfaces...

Bus error (core dumped)
```

This error was reported by @Eder-K in the [recent system tests](https://travis-ci.org/github/precice/systemtests/jobs/705575276#L15435) and I can reproduce it locally. 

I still need to investigate, if other data fields are affected as well, I guess there is something wrong in the destructors.

### PR DESCRIPTION
**Pull request by DavidSCN**
Resolves #133

### CODE REVIEW

**Comment by DavidSCN** [comment]
Got it now, the problem was the delete on the force field. I introduced another constructor (when created the stress) to avoid it's allocation, since it might be large. Therefore, I added now a boolean check in the destructor.

**Comment by DavidSCN** [comment]
> this is a hint that we need some change in the class hierarchy, not additional variables.

We could of course create a base class for both, Stress and Force to be fully consistent and circumvent the problem here. Also, we could introduce smart pointers, but this should be done consistently in all fields. These are all larger changes and more dedicated to general design principles, so, I don't like to spend more time working on this. However, note that the deal.II and openfoam systemtests fail due to this issue. 

You could either close this PR completely (it is linked in the issue anyway) or keep it open until a better solution is presented.

**Comment by DavidSCN** [comment]
@Eder-K does it fix the systemtest?

**Review by Eder-K — APPROVED** [review]

**Comment by DavidSCN** [comment]
@M

**Comment by DavidSCN** [comment]
@MakisH  I cannot merge for some reason, so please merge

**Comment by MakisH** [comment]
Somehow this was stuck in a `WIP` check. Everything looked good, so I merged it.

**Comment by Eder-K** [comment]
@MakisH could you also update the develop branch to include this change?

**Comment by MakisH** [comment]
@Eder-K I updated `develop`. I did not see that this was targetting `master`, and it has happened to me a few times. We need to fix this somehow. But we have a few more important things to fix first.

**Pull request merged**
