### PR TITLE
Add pre-commit for liniting docs

### PR DESCRIPTION
**Pull request by fsimonis**
This PR adds pre-commit hooks for linting the markdown docs as well as ensuring added images have the correct prefix.

### CODE REVIEW

**Comment by fsimonis** [comment]
The corresponding workflow is still missing.
Which branches need to be checked?

**Comment by fsimonis** [comment]
Done. I removed the markdown workflow as it is now covered by pre-commit.

**Comment by MakisH** [comment]
Can you please also add a quick mention in the CONTRIBUTING.md?

https://github.com/precice/openfoam-adapter/blob/develop/CONTRIBUTING.md

**Comment by fsimonis** [comment]
Done

**Pull request merged**
