### PR TITLE
CHT: split code for preCICE adapter and openfoam

### PR DESCRIPTION
**Pull request by TEFEdotCC**
These pull request change the CHT module in an radiacal way. It moves the openfoam code of the CHT module into an boundary condition and seperate on that way the preCICE code and openfoam code which is needed for that adapter.

The main benifit for the split is the possibility to move the boundary condition to the openfoam developer or migrate the code into the [externalWallHeatFlux](https://www.openfoam.com/documentation/guides/latest/api/classFoam_1_1externalWallHeatFluxTemperatureFvPatchScalarField.html) boundary, which is already present.

 - [x] **Split code for openfoam and preCICE parts of the adapter.**
 - [x] Introduce a new boundary condition for external api based wall heat transfer.
 - [x] Usage of openfoam way to provide missing informations (0 directory, usage of fields)
 - [x] **All relevant solver are supported.**
 - [x] **Radiation support implemented.**
 - [x] Introduce the Core directory for the adapter code files.
 - [x]  Check CHT equations and implementation
 - [ ] Idependents check of the implemented CHT equations (4 eyes principle)
 - [x] Run *flow over plate* (heatflux, heat-sink and neighbour mapping) examples successfull
 - [ ] Add further examples (for all solvers with cases for verification and practicable work)
 - [x] Remove raw 'new' and 'delete' operators on some places and replaced it with C++ standard features,
 - [x] Replace raw types (int, double, ...) with openfoam types if it was possible.
 - [x] Add checks if openfoam label size is 64bit for possible overflows.
 - [x] Reader and Writes: Remove pointers with references.
 - [x] Move and merge tutorials to examples directory.
 - [ ] preciceDict modules: Remove the possibility to enable/disable of CHT, FSI, .. module. Use case where the feature is needed?
 - [ ]  preciceDict and selection of readers and writers by name: Change the implicit selection behaviour by name to explicit selection by type. `readData( FieldName )` --> `readData( (FieldName, Type) )` . see #138 for more
 - [ ] **Offical documentation must be rewrite for usage the CHT module.**
 - [ ] #77, #142, #143
- [x] Builds with OpenFOAM [v1912](https://develop.openfoam.com/Development/openfoam/-/tree/d19515bfb8bb1c61945cf328aba591a4787a4df7), [v2006](https://develop.openfoam.com/Development/openfoam/-/tree/5e660c36e9d863ceea6399b3eaffc228879fbda7), develop [79a4dc51](https://develop.openfoam.com/Development/openfoam/-/tree/79a4dc5153c9ab51ec7d3a6c1c9f36c940c54fcd)
 
 I implemented these due to need an fast solution for my case with the icoReactingMultiphaseInterFoam solver. The actually adapter do not working with that solver.
 So, I share my changes and there are free for discussions.
 See also to my Github [repository](https://github.com/TEFEdotCC/Containered-OpenFOAM.com) for an docker container with the latest openfoam.com release and modified openfoam-adapter.
 
The ideas (#77, #142 and #143) to use of present function objects, usage with the **externalFileCoupler**, should be the best way in my mind for the future with minimum maintance cost for the adapter. The case setup maybe gets more complexity.

Maybe I look forward in the next weeks / month to implement the CHT modul on function objects, the ideas behind the externalFileCoupler and use the results for this adapter. An possible solution should also working for the FSI module.

### CODE REVIEW

**Comment by MakisH** [comment]
This is huge, but implements many changes I also wanted to see here. Thank you for all the work until now and let me know when you are ready to start the review iterations.

**Comment by TEFEdotCC** [comment]
Next week would be a good start point for an review.
I didn't think that the pull request will be accepted. So, I fix some parts at the description and implementation to an smooth some parts.

**Comment by MakisH** [comment]
If it becomes clean ans specific enough yes, I would vote for merging it. :-)

Smaller PRs will definitely easier to review, but let's see what we can get!

**Comment by TEFEdotCC** [comment]
Yeah, sorry for the big case ;-)
Bavarian people likes big cases :D

@MakisH Maybe an review in an munich/rosenheim bar next month? ;) .... Perhaps a personal meeting to union a network on both sides. See what the month will be bring in the next time.

**Comment by TEFEdotCC** [comment]
@MakisH 
Please start the review. I'm also very busy ... actually it is an hobby project. I'm looking forward to your requests for changes.

One question from my side is the possibility of user scripted code for heatflux, thc, ..etc.
Should we enable the possibility generally?
(Adding for heatflux, h_neighbour / T_neighbour patch scripting function and add that to the api values)? **Pointer checks would be necessary.**

**Comment by TEFEdotCC** [comment]
Ahh ... after reviewing CHT module and I will looking for the FSI module.

Note: the actually calculation of  the water heater example looks good. As soon as I had results for the entry simulation time I will post an update on my blog. (link coming soon as possible)

**Comment by MakisH** [comment]
> @MakisH Maybe an review in an munich/rosenheim bar next month? ;) .... Perhaps a personal meeting to union a network on both sides. See what the month will be bring in the next time.

@TEFEdotCC you 've got mail! :incoming_envelope: I sent to your tefe.cc address, I hope this was the right place.

**Comment by TEFEdotCC** [comment]
The result temperature and volume fraction field of my first study.
https://blog.tefe.cc/post/2020/01-watercooker#the-results

**Comment by TEFEdotCC** [comment]
Successfull build with OpenFOAM maintance versions
 - [v1912](https://develop.openfoam.com/Development/openfoam/-/tree/d19515bfb8bb1c61945cf328aba591a4787a4df7)
 - [v2006](https://develop.openfoam.com/Development/openfoam/-/tree/5e660c36e9d863ceea6399b3eaffc228879fbda7)
 - develop [79a4dc51](https://develop.openfoam.com/Development/openfoam/-/tree/79a4dc5153c9ab51ec7d3a6c1c9f36c940c54fcd)

**Pull request closed without merging**
