### PR TITLE
Change xy-plane check error to warning

### LINKED ISSUE #228: Enable 2d axisymmetric cases
For 2d cases with a wedge for axisymmetric simulation this causes an error. I'd suggest to change that to a warning.

https://github.com/precice/openfoam-adapter/blob/a95da52062c2f503ce58d9509c3e47f5efdbf149/Interface.C#L156

### PR DESCRIPTION
**Pull request by MakisH**
This adds support for axisymmetric cases, closes #228.

@arvedes FYI (I also directly used the `adapterInfo` function). Thanks for contributing the suggestion!

@davidscn please do a sanity check. In #228, you suggested a more elaborate fix, but according to @arvedes, this is already enough for his use case.

TODO list:

- [x] I updated the documentation in `docs/`
- [x] I added a changelog entry in `changelog-entries/` (create directory if missing)
- [ ] Squash before merging

### CODE REVIEW

**Comment by arvedes** [comment]
Great, thanks a lot!

**Review by davidscn — COMMENTED** [review]
> you suggested a more elaborate fix, but according to @arvedes, this is already enough for his use case.

Well, of course it is enough, as it removes now the barrier completely, whereas my idea was to remove the barrier only conditional. There is not much to review here, if you think that it is safe enough, feel free to merge,

**Comment by MakisH** [comment]
> > you suggested a more elaborate fix, but according to @arvedes, this is already enough for his use case.
> 
> Well, of course it is enough, as it removes now the barrier completely, whereas my idea was to remove the barrier only conditional. There is not much to review here, if you think that it is safe enough, feel free to merge,

A malformed case should anyway crash later or for other reasons, right? So, a warning should be enough here to understand what went wrong (assuming a user would look at the beginning of the log).

**Comment by davidscn** [comment]
This concern is only about usability, yes.

**Pull request merged**
