### PR TITLE
Bump default OpenFOAM version to v2306

### PR DESCRIPTION
**Pull request by MakisH**
- Replaces the default OpenFOAM version from v2212 to v2306 in the README and default CI workflow, and switches the default Ubuntu version to 22.04
- Adds v2306 and Ubuntu 22.04 to the custom build workflow
- Replaces the default preCICE version from v2.3.0 to v2.5.0 in the custom build workflow (not that it matters, but v2.3.0 was a strange default)

A separate PR in the tutorials will update the Quickstart.

TODO list:

- [x] I updated the documentation in `docs/`
- [x] I added a changelog entry in `changelog-entries/` (create directory if missing)

### CODE REVIEW

**Comment by MakisH** [comment]
Somehow, I always get an error that it cannot find the respective `openfoam2306-dev` package. Both for Ubuntu 22.04, as well as for 20.04. And same for `openfoam2212-dev`.

This looks strange, since previously we were building with `openfoam2212-dev` on Ubuntu 20.04, so at least this combination should work...

**Comment by MakisH** [comment]
There may be an issue with the package repository. Explicitly calling `apt update`, I get:

```
Ign:10 https://sourceforge.net/projects/openfoam/files/repos/deb jammy InRelease
Get:11 https://sourceforge.net/projects/openfoam/files/repos/deb jammy Release [2713 B]
Get:12 https://sourceforge.net/projects/openfoam/files/repos/deb jammy Release.gpg [862 B]
Get:13 https://sourceforge.net/projects/openfoam/files/repos/deb jammy/main all Packages [5598 B]
Err:13 https://sourceforge.net/projects/openfoam/files/repos/deb jammy/main all Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:5598 [weak]
   - SHA256:a43f5b2c3c8cfaba4bee242b13f68090f9d529e85b95d122cb9ecbda4132befb
   - SHA1:bf6e59a652e6f2ea64e5c69e05f58e207ef6b428 [weak]
   - MD5Sum:931c0b25ac1076b4aafd078faa2c2574 [weak]
  Hashes of received file:
   - SHA256:17c89d37f17e69b080a614398605b9e5a49d769d9eb6209c70088a19dee04c6b
   - SHA1:00d0b9c37f9c074980eb4a7975954b835c268dcb [weak]
   - MD5Sum:8c193ac9dc82c9cd1d69f746081b5a1f [weak]
   - Filesize:5598 [weak]
  Last modification reported: Fri, 30 Jun 2023 10:16:51 +0000
  Release file created at: Tue, 18 Jul 2023 16:37:57 +0000
Fetched 9173 B in 7s (1406 B/s)
Reading package lists...
E: Failed to fetch https://gigenet.dl.sourceforge.net/project/openfoam/repos/deb/dists/jammy/main/binary-all/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:5598 [weak]
    - SHA256:a43f5b2c3c8cfaba4bee242b13f68090f9d529e85b95d122cb9ecbda4132befb
    - SHA1:bf6e59a652e6f2ea64e5c69e05f58e207ef6b428 [weak]
    - MD5Sum:931c0b25ac1076b4aafd078faa2c2574 [weak]
   Hashes of received file:
    - SHA256:17c89d37f17e69b080a614398605b9e5a49d769d9eb6209c70088a19dee04c6b
    - SHA1:00d0b9c37f9c074980eb4a7975954b835c268dcb [weak]
    - MD5Sum:8c193ac9dc82c9cd1d69f746081b5a1f [weak]
    - Filesize:5598 [weak]
   Last modification reported: Fri, 30 Jun 2023 10:16:51 +0000
   Release file created at: Tue, 18 Jul 2023 16:37:57 +0000
E: Failed to fetch https://downloads.sourceforge.net/project/openfoam/repos/deb/dists/jammy/main/binary-amd64/Packages.gz?download&failedmirror=gigenet.dl.sourceforge.net  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by MakisH** [comment]
If I go to https://sourceforge.net/projects/openfoam/files/repos/deb/dists/jammy/main/binary-all/ and download `Packages.gz`, I get the expected sha256sum. If I follow the (mirror?) link that APT reports, I get the reported one. The modification date seems to be different.

```text
New - expected: https://sourceforge.net/projects/openfoam/files/repos/deb/dists/jammy/main/binary-all/
a43f5b2c3c8cfaba4bee242b13f68090f9d529e85b95d122cb9ecbda4132befb
last modified: Tue Jul 18 16:36:29 2023

Old - received: https://gigenet.dl.sourceforge.net/project/openfoam/repos/deb/dists/jammy/main/binary-all/Packages.gz
17c89d37f17e69b080a614398605b9e5a49d769d9eb6209c70088a19dee04c6b
last modified: Fri Jun 30 10:16:51 2023
```

@olesenm does this issue sound familiar? I can imagine that Sourceforge has not updated some mirrors or similar.

**Comment by olesenm** [comment]
looks like a bad value there - will have to check with andy if all of the packages were sync'd across.

**Comment by MakisH** [comment]
@olesenm unless you triggered something, time seems to have fixed the problem already. Thanks for the answer!

**Review by davidscn — APPROVED** [review]

**Pull request merged**
