### PR TITLE
Remove boundary evaluation for checkpointing

### PR DESCRIPTION
**Pull request by DavidSCN**
First workaround for #4

Using these few lines of code, we could circumvent the error, which is triggered by `correctBoundaryConditions()` on the epsilonWallFunction bc type. This is a first step and not the final solution, since there are also other issues,(#92 #15) which have a similar problem and we want to find a more general solution. 
We still don't know in detail, if we need the function call (=what it does).

### CODE REVIEW

**Comment by MakisH** [comment]
Is this ready to review?

**Comment by DavidSCN** [comment]
Yes. Although it basically removes the boundary evaluation and corresponding warnings.

The only thing we still need to adapt (remove) is the option in the OF dict.

**Comment by MakisH** [comment]
> The only thing we still need to adapt (remove) is the option in the OF dict.

Could you please also prepare this in the same PR?

Also, could you please give a more descriptive title and remove the "WIP"?

**Comment by DavidSCN** [comment]
Done so far. There are a few lines with a removed spacing, which appear in the commit, sorry for that.

This PR would close #4, #15 and #92.

**Pull request merged**
